### ISSUE TITLE
Consider using extra section instead of config

### ISSUE THREAD

**Issue by JanTvrdik** [dg/composer-cleaner#11]
- bug report? maybe

The `config` key is intended to be used by Composer itself, Composer plugins should use the key `extra`. Using `config` key does not currently AFAIK cause any issues, but may cause problems in the future.

See https://getcomposer.org/schema.json:
* the `config` key is described as „Composer options.“
* the `extra` key is described as „Arbitrary extra data that can be used by plugins, for example, package of type composer-plugin may have a 'class' key defining an installer class name.“

**Comment by dg** [comment]
I do not know how to get `extra` data.

**Comment by JanTvrdik** [comment]
Looking at Composer repo it looks like `$event->getComposer()->getPackage()->getExtra()` should work.
