### ISSUE TITLE
Removing most of the files in a new package (mpdf/mpdf)

### ISSUE THREAD

**Issue by maral** [dg/composer-cleaner#15]
- bug report? yes
- feature request? no

### Description
Not quite sure what is happening. I asked at StackOverflow and it was answered. I don't think this is a feature.
https://stackoverflow.com/questions/46195321/composer-removing-random-files-from-package-after-installation/46212934#46212934

### Steps To Reproduce
`composer require dg/composer-cleaner`
`composer require mpdf/mpdf`

**Comment by dg** [comment]
Duplicate to #14
